# Generated by Django 5.0.2 on 2024-11-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='short_urls',
        ),
    ]
